-- AlterTable
ALTER TABLE `Timer` 
    MODIFY `link` TEXT NOT NULL,
    ADD COLUMN `endTime` DATETIME(3) NULL,
    ADD COLUMN `organizers` TEXT NULL,
    MODIFY `logo` VARCHAR(500) NULL,
    ADD COLUMN `slug` VARCHAR(100) NULL,
    ADD COLUMN `isMeta` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `metaId` VARCHAR(255) NULL,
    ADD COLUMN `participation` VARCHAR(100) NULL,
    ADD COLUMN `eventTypes` TEXT NULL,
    ADD COLUMN `topics` TEXT NULL,
    ADD COLUMN `wikiProject` VARCHAR(100) NULL,
    ADD COLUMN `isCancelled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

-- CreateIndex
CREATE UNIQUE INDEX `Timer_metaId_key` ON `Timer`(`metaId`);
